<!-- FlexShopper Logo -->
<img src="<?php echo $this->escapeHtml($this->getFlexLogoSrc())?>" alt="<?php echo Mage::helper('flexpayment')->__('FlexShopper') ?>" class="v-middle" />&nbsp;
<?php /*
<a href="<?php echo $this->getFlexHref()?>" onclick="javascript:window.open('<?php echo $this->getFlexHref()?>','whatisflex','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=0, top=0, width=400, height=350'); return false;"><?php echo Mage::helper('flexpayment')->__('What is FlexShopper?') ?></a>
*/ ?>
<!-- FlexShopper Logo -->
